### ISSUE TITLE
Unable to connect to Cockpit in Virtual Appliance

### ISSUE THREAD

**Issue by GitMarshallBill** [NEMSLinux/nems-admin#12]
In Virtual Appliance receiving Unable to connect, Connection refused when attempting to use Cockpit via port 9090

**Comment by NEMSLinux** [comment]
Thanks. There are 3 virtual appliances. Which one specifically are you using (just so I can rule it out). Cheers!

**Comment by GitMarshallBill** [comment]
So far just ESXi 7.0 so the ova file

**Comment by GitMarshallBill** [comment]
Works on Virtualbox. May be my implementation

**Comment by NEMSLinux** [comment]
Alright, cool - thanks. I'm also using ESXi 7.0 and it worked before I released it... so I'll dig into it and update you - thanks for letting me know!

**Comment by NEMSLinux** [comment]
We posted at the same time :)

Got it. I assume you've tried obvious things like rebooting? Does `systemctl status cockpit` show anything of interest?

**Comment by GitMarshallBill** [comment]
My NEMS instance is showing 2 IP addresses 

scope global dynamic noprefixroute ens160
scope global secondary dynamic noprefixroute ens160

Probably the issue

**Comment by GitMarshallBill** [comment]
Rebuilt the VM. Works now

**Comment by GitMarshallBill** [comment]
Once I created the reservation for the VM on my DHCP server the second address went away
