### ISSUE TITLE
Unable to run nrpe after getting the repo via github

### ISSUE THREAD

**Issue by Azokul01** [NEMSLinux/nems-admin#13]
The repo at https://raw.githubusercontent.com/Cat5TV/nems-admin/master/build/047-nrpe is currently missing some files (nrpe.cfg and nrpe on /usr/local/nagios/bin/nrpe)

**Comment by NEMSLinux** [comment]
Moved to correct repository: https://github.com/NEMSLinux/nems-plugins/issues/13
