### ISSUE TITLE
Unable to add logo on XU4 v1.6

### ISSUE THREAD

**Issue by GitMarshallBill** [NEMSLinux/nems-admin#14]
To add logo you need a vendor folder in /boot. There is only a FILE called vendor

**Comment by NEMSLinux** [comment]
This also impacted Raspberry Pi 5 during build of 1.7, so has been fixed. It will not be backported; instead, we should just consider this feature broken in 1.6 and move to 1.7 when it is released. Thanks @GitMarshallBill !
