### ISSUE TITLE
question: does nems-restore restores custom check-scripts as well?

### ISSUE THREAD

**Issue by manhofmann** [NEMSLinux/nems-admin#20]
Hello,

scripts of checkcommands are saved in /usr/lib/nagios/plugins
If i have my own scripts added into this directory and created my own check commands in NConf as well do i have to manually add those scripts again or does nems-restore take care of it?

**Comment by NEMSLinux** [comment]
This is not an issue. Please use appropriate means of obtaining support from the developer, the community, or the documentation.
