### ISSUE TITLE
Speed test on 1.6

### ISSUE THREAD

**Issue by ChrisHird** [NEMSLinux/nems-admin#7]
Does not work here is the debug information
Debug for the speed test issue
[[u'Total Processes', 0, 1, u'PROCS OK: 64 processes with STATE = RSZDT'], [u'SSH', 0, 1, u'SSH OK - OpenSSH_7.9p1 Raspbian-10+deb10u2+rpt1 (protocol 2.0)'], [u'Root Partition', 0, 1, u'DISK OK - free space: / 108 GB (96% inode=98%):'], [u'NEMS Migrator Off-Site Backup', 3, 1, u'NEMS Cloud Services not authorized.'], [u'NEMS Current Load', 0, 1, u'OK - load average: 0.28, 0.49, 0.55'], [u'Internet Speed Test', 2, 1, u'(Service check timed out after 121.10 seconds)'], [u'HTTP', 0, 1, u'HTTP OK: HTTP/1.1 200 OK - 16342 bytes in 2.986 second response time'], [u'Current Users', 0, 1, u'USERS OK - 0 users currently logged in'], [u'CPU Temperature', 0, 1, u'TEMPERATURE OK - CPU Temp: 48.199 \xb0C / 118.758 \xb0F']]

**Comment by NEMSLinux** [comment]
I suspect this is to do with the beta repository move. Please patch your nems.list or upgrade to the 1.6 Release Candidate as soon as it is released. Let me know once you are on the RC if the issue remains.
